name = "multipost-seo-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "accountsmultipostapp"
database_id = "19dfae46-a6cb-4e88-ab7c-2ab2fea3279a"

[ai]
binding = "AI"
